# Generated by Django 2.2.3 on 2020-04-14 02:50

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200413_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=mdeditor.fields.MDTextField(verbose_name='正文'),
        ),
    ]
